[tools]
odin = "dev-2025-12a"

[tools."github:larzconwell/ols"]
version = "nightly"

[tasks.setup]
description = "Sets up for development"
run = [
  "mise install",
  "ln -sf {{cwd}}/scripts/format_check .git/hooks/pre-commit"
]

[tasks.build]
description = "Builds chess binary"
run = "odin build . -out:chess -show-timings -strict-style -vet -warnings-as-errors"

[tasks.play]
description = "Build and run"
run = "odin run . -show-timings -strict-style -vet -warnings-as-errors"

[tasks.format]
description = "Format code"
run = "./scripts/format"

[tasks.format_check]
description = "Checks if code is formatted"
run = "./scripts/format_check"
